### ISSUE TITLE
Unable to install python3-asyncore

### ISSUE THREAD

**Issue by Devorak-creator** [simonrob/pyasyncore#3]
I am working on Kali Linux and having trouble installing asyncore in python 3.12 while upgrading using `sudo apt upgrade` . I also tried `sudo apt-get install python3-pyasyncore` , `pip install pyasyncore ` and `sudo apt --fix-broken install` but still unable to install. The problem comes when unpacking  : 

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 48
  6 not fully installed or removed.
  Download size: 0 B / 10.3 kB
  Space needed: 44.0 kB / 280 GB available

Continue? [Y/n] y
(Reading database ... 940265 files and directories currently installed.)
Preparing to unpack .../python3-asyncore_1.0.4-0kali1_all.deb ...
Unpacking python3-asyncore (1.0.4-0kali1) ...
dpkg: error processing archive /var/cache/apt/archives/python3-asyncore_1.0.4-0k
ali1_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/asyncore/__init__.py', whic
h is also in package python3-pyasyncore 1.0.2-2
Errors were encountered while processing:
 /var/cache/apt/archives/python3-asyncore_1.0.4-0kali1_all.deb
Error: Sub-process /usr/bin/dpkg returned an error code (1) 

and 

`sudo apt-get install python3-pyasyncore`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyasyncore is already the newest version (1.0.2-2).
python3-pyasyncore set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 odat : Depends: python3-asyncore but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

I have also tried software store and it stops after 5% and shows error : 

Error while installing package: trying to overwrite '/usr/lib/python3/dist-packages/asyncore/__init__.py', which is also in package python3-pyasyncore 1.0.2-2

**Comment by simonrob** [comment]
Thanks for reporting this. I'm afraid there's not much I can do here – I'm not responsible for the `python3-pyasyncore` Linux package, only the underlying python module as found in this repository. Can you `sudo apt-get remove python3-pyasyncore` and instead [use `pip` to install `pyasyncore`](https://pypi.org/project/pyasyncore/)?

**Comment by simonrob** [comment]
I'm assuming this was resolved, so will close this issue, but feel free to reopen if you can provide more details to reproduce.
